# This file was generated by the {rix} R package v0.17.2 on 2025-11-08
# with following call:
# >rix(date = "2024-12-14",
#  > r_pkgs = c("Rcpp",
#  > "RcppArmadillo",
#  > "RcppEigen",
#  > "BH",
#  > "data.table",
#  > "Matrix",
#  > "matrixStats",
#  > "foreach",
#  > "doParallel",
#  > "future",
#  > "parallel",
#  > "remotes",
#  > "pak",
#  > "tidyverse",
#  > "readxl",
#  > "glmnet",
#  > "e1071",
#  > "ranger",
#  > "caret",
#  > "lme4",
#  > "mclust",
#  > "MCMCpack",
#  > "huge",
#  > "nnls",
#  > "moments",
#  > "pracma",
#  > "gridExtra",
#  > "gplots",
#  > "RColorBrewer",
#  > "plotly",
#  > "heatmaply",
#  > "ggpubr",
#  > "ggtext",
#  > "corrplot",
#  > "png",
#  > "colorspace",
#  > "scales",
#  > "R.devices",
#  > "DT",
#  > "kableExtra",
#  > "BiocManager",
#  > "SummarizedExperiment",
#  >      "limma",
#  > "vsn",
#  > "AnnotationDbi",
#  > "biomaRt",
#  > "ExperimentHub",
#  > "ComplexHeatmap",
#  > "Biostrings",
#  > "IRanges",
#  > "S4Vectors",
#  > "zlibbioc",
#  > "sva",
#  > "batchelor",
#  > "RUVSeq",
#  > "MLmetrics",
#  > "ROCR",
#  > "xgboost",
#  > "lightgbm",
#  > "parsnip",
#  > "tidymodels",
#  > "Rtsne",
#  > "umap",
#  > "argparse",
#  > "docstring",
#  > "itertools",
#  > "pacman",
#  > "stringi",
#  > "magick",
#  > "bigmemory",
#  > "Seurat",
#  > "fairadapt",
#  > "seqgendiff",
#  > "logspline",
#  > "languageserver"),
#  > system_pkgs = c("openssl",
#  > "curl",
#  > "libxml2",
#  > "fontconfig",
#  > "harfbuzz",
#  > "fribidi",
#  > "freetype",
#  > "libpng",
#  >      "libtiff",
#  > "libjpeg",
#  > "libwebp",
#  > "imagemagick",
#  > "glpk",
#  > "gsl",
#  > "udunits"),
#  > git_pkgs = NULL,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE,
#  > r_ver = "4.4.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/refs/heads/2024-12-14.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      AnnotationDbi
      BH
      BiocManager
      Biostrings
      ComplexHeatmap
      DT
      ExperimentHub
      IRanges
      MCMCpack
      MLmetrics
      Matrix
      R_devices
      RColorBrewer
      ROCR
      RUVSeq
      Rcpp
      RcppArmadillo
      RcppEigen
      Rtsne
      S4Vectors
      Seurat
      SummarizedExperiment
      argparse
      batchelor
      bigmemory
      biomaRt
      caret
      colorspace
      corrplot
      data_table
      doParallel
      docstring
      e1071
      fairadapt
      foreach
      future
      ggpubr
      ggtext
      glmnet
      gplots
      gridExtra
      heatmaply
      huge
      itertools
      kableExtra
      languageserver
      lightgbm
      limma
      lme4
      logspline
      magick
      matrixStats
      mclust
      moments
      nnls
      pacman
      pak
      parsnip
      plotly
      png
      pracma
      ranger
      readxl
      remotes
      scales
      seqgendiff
      stringi
      sva
      tidymodels
      tidyverse
      umap
      vsn
      xgboost
      zlibbioc;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      R
      curl
      fontconfig
      freetype
      fribidi
      glibcLocales
      glpk
      gsl
      harfbuzz
      imagemagick
      libjpeg
      libpng
      libtiff
      libwebp
      libxml2
      nix
      openssl
      udunits;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
