# ==============================================================================
# SCRIPT 3: plot_performance.R
#
# This script reads the 'performance_log.csv' generated by the profiling
# script and creates plots to visualize the time complexity.
#
# USAGE:
# 1. Make sure you have the required packages: install.packages(c("ggplot2", "readr", "dplyr"))
# 2. Run the script in R or RStudio: Rscript plot_performance.R
# ==============================================================================

# Load required packages
suppressPackageStartupMessages({
  library(ggplot2)
  library(readr)
  library(dplyr)
})

# --- Load and Process Data ---
log_file <- "/outputs/performance_log.csv"
if (!file.exists(log_file)) {
  stop(sprintf("Performance log file not found: '%s'. Please run the profiling script first.", log_file))
}
perf_data <- read_csv(log_file, show_col_types = FALSE)

# Find the fixed values used during profiling
fixed_col_value <- perf_data$cols[perf_data$rows == max(perf_data$rows)][1]
fixed_row_value <- perf_data$rows[perf_data$cols == max(perf_data$cols)][1]

# Separate the data from the two experimental runs
row_profiling_data <- perf_data %>% filter(cols == fixed_col_value)
col_profiling_data <- perf_data %>% filter(rows == fixed_row_value)

# --- Plot Time vs. Number of Rows ---
plot_rows <- ggplot(row_profiling_data, aes(x = rows, y = real_time)) +
  geom_point(size = 3, aes(color = "Measured Time")) +
  geom_line(aes(color = "Measured Time")) +
  # Optional: Add a smoothed line to see the trend
  geom_smooth(method = "loess", formula = 'y ~ x', se = FALSE, aes(color = "Trend")) +
  scale_color_manual(name = "", values = c("Measured Time" = "steelblue", "Trend" = "firebrick")) +
  labs(
    title = "Script Performance vs. Number of Rows (Samples)",
    subtitle = sprintf("Number of columns held constant at %s", format(fixed_col_value, big.mark = ",")),
    x = "Number of Rows",
    y = "Execution Time (seconds)"
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "bottom")

# Save the plot
ggsave("performance_vs_rows.png", plot = plot_rows, width = 8, height = 6, dpi = 100)
print(plot_rows)


# --- Plot Time vs. Number of Columns ---
plot_cols <- ggplot(col_profiling_data, aes(x = cols, y = real_time)) +
  geom_point(size = 3, aes(color = "Measured Time")) +
  geom_line(aes(color = "Measured Time")) +
  geom_smooth(method = "loess", formula = 'y ~ x', se = FALSE, aes(color = "Trend")) +
  scale_color_manual(name = "", values = c("Measured Time" = "darkgreen", "Trend" = "orange")) +
  labs(
    title = "Script Performance vs. Number of Columns (Features)",
    subtitle = sprintf("Number of rows held constant at %s", format(fixed_row_value, big.mark = ",")),
    x = "Number of Columns",
    y = "Execution Time (seconds)"
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "bottom")

# Save the plot
ggsave("performance_vs_cols.png", plot = plot_cols, width = 8, height = 6, dpi = 100)
print(plot_cols)

message("\nPerformance plots have been saved to 'performance_vs_rows.png' and 'performance_vs_cols.png'")

