# config.yaml

output_folder: "/grphome/grp_batch_effects/outputs/metadata_features"
data_folder: "/grphome/grp_batch_effects/data"
scripts_dir: "."
adjust_script: "../../adjust/adjust.R"
scaling_script: "../classify_er_all_datasets/run_scaling_experiment.R"

adjusters: ["gmm", "min_mean", "mnn", "log_combat", "log_transformed"]
dataset_ids:
  - "gse19615"
  - "gse20194"
  - "gse20271"
  - "gse23720"
  - "gse25055"
  - "gse25065"
  - "gse31448"
  - "gse45255"
  - "gse58644"
  - "gse62944_tumor"
  - "gse76275"
  - "gse81538"
  - "gse96058_hiseq"
  - "gse96058_nextseq"
  - "metabric"

targets: [
  'meta_er_status', 
  'meta_her2_status', 
  'meta_sex', 
  'meta_chemotherapy', 
  'meta_age_at_diagnosis_combined_lt50', 
  'meta_age_at_diagnosis_combined_50_69', 
  'meta_age_at_diagnosis_combined_ge70', 
  'meta_menopause_status',
  'meta_histological_type'
]

test_sources:
- "metabric"

dataset_list: 
- "metabric" 
- "gse62944_tumor"

# Permutation importance
n_repeats: 3
n_jobs: 4
random_state: 42

# Feature Selection
top_k: 100
threshold: 0.05