configfile: "config.yaml"

import os

# -------------------------
# Config
# -------------------------
OUT_DIR = config["out_dir"]
DATA_DIR = config["data_dir"]
SCRIPTS_DIR = config.get("scripts_dir", ".")
ADJUST_SCRIPT = config.get("adjust_script", "../../adjust/adjust.R")
SCALING_SCRIPT = config.get("scaling_script", "../classify_er_all_datasets/run_scaling_experiment.R")
COMBINED_FILE = config["combined_file"]
GEO_METADATA = config["geo_metadata"]

ADJUSTERS = config["adjusters"]
TARGETS = config["targets"]
K_VALUES = [2]
TEST_SOURCES = config["test_sources"]

TOP_K = config["top_k"]
THRESHOLD = config["threshold"]

N_REPEATS = config["n_repeats"]
N_JOBS = config["n_jobs"]
RANDOM_STATE = config["random_state"]

SUBSET_DIR = os.path.join(DATA_DIR, "subset")
ADJUST_DIR = os.path.join(DATA_DIR, "adjusted")
CLASSIFY_DIR = os.path.join(DATA_DIR, "classify")
TTEST_DIR = os.path.join(DATA_DIR, "ttest")
GENE_LIST_DIR = os.path.join(DATA_DIR, "top_genes")
PLOT_DIR = os.path.join(OUT_DIR, "plots")

wildcard_constraints:
    test_source="|".join(TEST_SOURCES),
    adjuster="|".join(ADJUSTERS),
    target="|".join(TARGETS),
    k="|".join(map(str, K_VALUES))

# -------------------------
# All targets
# -------------------------
rule all: 
    input:
        expand(
            os.path.join(TTEST_DIR, "{adjuster}", "{adjuster}-{k}_studies-test_{test_source}-tstats.csv"),
            adjuster=ADJUSTERS,
            k=K_VALUES,
            test_source=TEST_SOURCES
        )

# -------------------------
# Subset datasets
# -------------------------
rule subset:
    input: 
        combined_file=COMBINED_FILE
    output: 
        subset_file=os.path.join(SUBSET_DIR, "test_{test_source}-subset.csv")
    log: 
        "logs/subset/{test_source}-subset.log"
    resources:
        mem_mb=8000,
        runtime=30
    params:
        data_list=" ".join(config['dataset_list'])
    shell:
        """
        python {SCRIPTS_DIR}/subset_datasets.py \
            --input {input.combined_file} \
            --test {wildcards.test_source} \
            --dataset_list {params.data_list} \
            --out_dir {SUBSET_DIR} \
            > {log} 2>&1
        """

# -------------------------
# Align metadata
# -------------------------
rule align_metadata:
    input: 
        subset=os.path.join(SUBSET_DIR, "test_{test_source}-subset.csv")
    output:
        aligned=os.path.join(SUBSET_DIR, "metadata_aligned-{test_source}.csv")
    log:
        "logs/align/{test_source}-alignment.log"
    resources:
        mem_mb=4000,
        runtime=30
    shell:
        """
        python {SCRIPTS_DIR}/align_metadata.py \
            --input {input.subset} \
            --output {output.aligned} \
            > {log} 2>&1
        """

# -------------------------
# Adjust datasets
# -------------------------
rule adjust: 
    input: 
        aligned=os.path.join(SUBSET_DIR, "metadata_aligned-{test_source}.csv")
    output: 
        adjusted=os.path.join(
            ADJUST_DIR,
            "{adjuster}",
            "{adjuster}-{k}_studies-test_{test_source}.csv"
        )
    log: 
        "logs/adjust/{adjuster}-{k}_{test_source}-adjust.log"
    resources:
        mem_mb=32000,
        runtime=30
    params:
        output_dir=ADJUST_DIR,
        adjust_script=ADJUST_SCRIPT,
        metadata=GEO_METADATA
    shell:
        """
        set -euo pipefail
        pixi run Rscript {SCALING_SCRIPT} \
            --adjuster {wildcards.adjuster} \
            --subset-path {input.aligned} \
            --k {wildcards.k} \
            --test {wildcards.test_source} \
            --output-dir {params.output_dir} \
            --adjust-script {params.adjust_script} \
            --metadata-file {params.metadata} \
            > {log} 2>&1
        """

# ------------------------
# T-Test
# ------------------------
rule ttest:
    input:
        csv=os.path.join(ADJUST_DIR, "{adjuster}", "{adjuster}-{k}_studies-test_{test_source}.csv")
    output:
        tstats=os.path.join(TTEST_DIR, "{adjuster}", "{adjuster}-{k}_studies-test_{test_source}-tstats.csv")
    log:
        "logs/ttest/{adjuster}-{k}-{test_source}-train.log"
    shell:
        """
        python {SCRIPTS_DIR}/test_stats.py \
            --csv {input.csv} \
            --meta-cols {' '.join(TARGETS)} \
            --outdir {os.path.dirname(output.tstats)} \
            > {log} 2>&1
        """

# ------------------------
# Rank Genes
# ------------------------
rule rank_genes:
    input:
        csvs=lambda wc: expand(
            os.path.join(TTEST_DIR, "{adjuster}", "{adjuster}-{k}_studies-test_{test_source}-tstats.csv"),
            adjuster=ADJUSTERS,
            k=[wc.k],
            test_source=[wc.test_source]
        )
    output:
        ranked_dir=directory(os.path.join(GENE_LIST_DIR, "{k}_{test_source}"))
    log:
        "logs/rank/{k}_{test_source}.log"
    params:
        mode="tstat",   # change to slope / pval if needed
        agg="max_abs",
        threshold=0.0
    shell:
        """
        python {SCRIPTS_DIR}/rank_genes.py \
            --csvs {input.csvs} \
            --outdir {output.ranked_dir} \
            --mode {params.mode} \
            --agg {params.agg} \
            --threshold {params.threshold} \
            > {log} 2>&1
        """

# # -------------------------
# # Train models and compute metrics
# # -------------------------
# rule train_metrics:
#     input: 
#         csv=os.path.join(ADJUST_DIR, "{adjuster}", "{adjuster}-{k}_studies-test_{test_source}.csv")
#     output:
#         metrics=os.path.join(CLASSIFY_DIR, "{adjuster}", "{adjuster}-{k}_studies-test_{test_source}-metrics.csv")
#     log:
#         "logs/train/{adjuster}-{k}-{test_source}-train.log"
#     resources:
#         mem_mb=32000,
#         runtime=20
#     params: 
#         random_state=RANDOM_STATE 
#     shell:
#         """
#         python {SCRIPTS_DIR}/train_and_metrics.py \
#             --csv {input.csv} \
#             --outdir {CLASSIFY_DIR}/{wildcards.adjuster} \
#             --random_state {params.random_state} \
#             > {log} 2>&1
#         """
