# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hctree_sort_R <- function(distance_matrix, externalOrder, orderType, flipType) {
    .Call(`_GAPR_hctree_sort_R`, distance_matrix, externalOrder, orderType, flipType)
}

computeProximity_R <- function(data, proxType, side, isContainMissingValue) {
    .Call(`_GAPR_computeProximity_R`, data, proxType, side, isContainMissingValue)
}

ellipse_sort_R <- function(data) {
    .Call(`_GAPR_ellipse_sort_R`, data)
}

