# generate_plots.R
#
# This script reads coordinate files generated by a Python script
# and uses ggplot2 to create and save plots to a single PDF.
# It is the second step in a hybrid Python/R workflow.

suppressPackageStartupMessages({
  library(ggplot2)
  library(readr)
  library(argparse)
  library(tools)
})

# --- Main Execution Block ---
main <- function() {
  parser <- ArgumentParser(description = "Generate plots from pre-computed coordinate files.")
  parser$add_argument("-i", "--input-dir", required = TRUE, help = "Directory containing coordinate CSV files.")
  parser$add_argument("-o", "--output-pdf", required = TRUE, help = "Path to save the output PDF.")
  parser$add_argument("-d", "--dataset-name", required = TRUE, help = "Clean name for the dataset for plot titles.")
  args <- parser$parse_args()

  # Find all coordinate files in the input directory
  coord_files <- list.files(path = args$input-dir, pattern = "_coords.csv$", full.names = TRUE)

  if (length(coord_files) == 0) {
    stop("No coordinate files found in the input directory. Did you run the Python script first?")
  }
  
  plot_list <- list()

  for (file_path in coord_files) {
    message(paste("Generating plot for:", basename(file_path)))
    
    # Extract metadata from filename
    filename_parts <- strsplit(basename(file_path), "_")[[1]]
    method_name <- filename_parts[1]
    plot_type <- toupper(filename_parts[2])

    # Read the coordinate data
    plot_data <- readr::read_csv(file_path, col_types = cols())

    # --- Plot Creation (using the power of ggplot2) ---
    p <- ggplot(plot_data, aes(x = Dim1, y = Dim2, color = factor(Batch), shape = factor(TrueSignal))) +
      geom_point(size = 3, alpha = 0.8) +
      labs(
        title = paste(args$dataset_name, "-", tools::toTitleCase(method_name), paste0("(", plot_type, ")")),
        subtitle = "Colored by Batch, Shaped by True Biological Signal",
        x = paste0(plot_type, "-1"),
        y = paste0(plot_type, "-2"),
        color = "Batch",
        shape = "True Signal"
      ) +
      theme_bw(base_size = 14) +
      theme(
        legend.position = "bottom",
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)
      ) +
      guides(color = guide_legend(override.aes = list(size=4)),
             shape = guide_legend(override.aes = list(size=4)))
      
    plot_list[[basename(file_path)]] <- p
  }

  # --- Save all plots to a single PDF ---
  message(paste("Saving", length(plot_list), "plots to:", args$output_pdf))
  
  pdf(args$output_pdf, width = 11, height = 8.5)
  for (plot in plot_list) {
    print(plot)
  }
  dev.off()

  message("---")
  message(paste("Successfully generated:", args$output_pdf))
}

if (sys.nframe() == 0) {
  main()
}