# R version to bin directory path mapping for HPC
# Format: VERSION=BIN_PATH
# The version should match the r_version in rproject.toml

4.5.1=/apps/spack/root/opt/spack/linux-rhel9-haswell/gcc-13.2.0/r-4.5.1-264p7tzsobm57jhwvpte6ky7gzb45g7j/bin
4.5.0=/apps/spack/root/opt/spack/linux-rhel9-haswell/gcc-13.2.0/r-4.5.0-xcvdvruhvoiksfebvn3g3wqsjxyp3o27/bin
4.4.0=/apps/spack/root/opt/spack/linux-rhel9-haswell/gcc-13.2.0/r-4.4.0-o776kvtwhc3kxot2oqkv53kzmchecv4v/bin
4.3.3=/apps/spack/root/opt/spack/linux-rhel9-haswell/gcc-13.2.0/r-4.3.3-72k3zwrmjpftmtsw3aaaratszpl47e3g/bin
