// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hctree_sort_R
Rcpp::List hctree_sort_R(Rcpp::NumericMatrix distance_matrix, Rcpp::IntegerVector externalOrder, int orderType, int flipType);
RcppExport SEXP _GAPR_hctree_sort_R(SEXP distance_matrixSEXP, SEXP externalOrderSEXP, SEXP orderTypeSEXP, SEXP flipTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type distance_matrix(distance_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type externalOrder(externalOrderSEXP);
    Rcpp::traits::input_parameter< int >::type orderType(orderTypeSEXP);
    Rcpp::traits::input_parameter< int >::type flipType(flipTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(hctree_sort_R(distance_matrix, externalOrder, orderType, flipType));
    return rcpp_result_gen;
END_RCPP
}
// computeProximity_R
Rcpp::NumericMatrix computeProximity_R(Rcpp::NumericMatrix data, int proxType, int side, int isContainMissingValue);
RcppExport SEXP _GAPR_computeProximity_R(SEXP dataSEXP, SEXP proxTypeSEXP, SEXP sideSEXP, SEXP isContainMissingValueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type proxType(proxTypeSEXP);
    Rcpp::traits::input_parameter< int >::type side(sideSEXP);
    Rcpp::traits::input_parameter< int >::type isContainMissingValue(isContainMissingValueSEXP);
    rcpp_result_gen = Rcpp::wrap(computeProximity_R(data, proxType, side, isContainMissingValue));
    return rcpp_result_gen;
END_RCPP
}
// ellipse_sort_R
Rcpp::IntegerVector ellipse_sort_R(Rcpp::NumericMatrix data);
RcppExport SEXP _GAPR_ellipse_sort_R(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(ellipse_sort_R(data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GAPR_hctree_sort_R", (DL_FUNC) &_GAPR_hctree_sort_R, 4},
    {"_GAPR_computeProximity_R", (DL_FUNC) &_GAPR_computeProximity_R, 4},
    {"_GAPR_ellipse_sort_R", (DL_FUNC) &_GAPR_ellipse_sort_R, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_GAPR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
