# This file was generated by the {rix} R package v0.17.2 on 2025-11-08
# with following call:
# >rix(date = "2024-12-14",
#  > r_pkgs = c("BiocManager",
#  > "SummarizedExperiment",
#  > "ExperimentHub",
#  > "sva",
#  > "limma",
#  > "vsn",
#  > "ComplexHeatmap",
#  > "RUVSeq",
#  > "DESeq2",
#  > "batchelor",
#  > "data.table",
#  > "Matrix",
#  > "tidyverse",
#  > "dplyr",
#  > "ggplot2",
#  > "caret",
#  > "glmnet",
#  > "e1071",
#  > "MLmetrics",
#  > "ROCR",
#  > "argparse",
#  > "languageserver"),
#  > system_pkgs = c("openssl",
#  > "curl",
#  > "libxml2"),
#  > git_pkgs = NULL,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE,
#  > r_ver = "4.4.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/refs/heads/2024-12-14.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      BiocManager
      ComplexHeatmap
      DESeq2
      ExperimentHub
      MLmetrics
      Matrix
      ROCR
      RUVSeq
      SummarizedExperiment
      argparse
      batchelor
      caret
      data_table
      dplyr
      e1071
      ggplot2
      glmnet
      languageserver
      limma
      sva
      tidyverse
      vsn;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      R
      curl
      glibcLocales
      libxml2
      nix
      openssl;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
