# config.yaml

# Base folder for all final outputs, logs, and intermediate results
output_folder: "/home/phr23/confounded_analysis/grp_batch_effects/outputs/book_chapter"

# Folder containing input data
data_folder: "data"

scripts_folder: "scripts"

batch_effect_variances: [1, 3, 5]
batch_effect_means: [0.1, 3, 5, 10]
num_datasets: [3, 4, 5, 6]

classifiers: 
  - "logistic"
  - "elasticnet"
  - "svm"
  - "rf"
  - "nnet"
  - "knn"
  - "xgboost"
  - "rvc"

adjusters:
  - "unadjusted"
  - "combat"
  - "combat_mean"
  - "combat_sup"
  - "mnn"
  - "mnn_centered"
  - "ruvr"
  - "gmm"

# Adjusters to visualize (subset of adjusters for faster visualization)
viz_adjusters:
  - "unadjusted"
  - "combat"
  - "combat_mean"
  - "combat_sup"
  - "mnn"
  - "mnn_centered"

split_seed_start: 42
split_seed_count: 200