# config.yaml

# Base folder for all final outputs, logs, and intermediate results
output_folder: "grp_batch_effects/book_chapter"

# Folder containing input data
data_folder: "scripts/evaluations/book_chapter/data"

scripts_folder: "scripts/evaluations/book_chapter/scripts"

batch_effect_variances: [1, 3, 5]
batch_effect_means: [5]

classifiers: 
  - "logistic"
  - "elasticnet"
  - "svm"
  - "rf"
  - "knn"
  - "xgboost"
  - "nn"
  - "lightgbm"

adjusters:
  - "unadjusted"
  - "combat"
  - "mnn"
  - "ruv"
  - "sva"

split_seed_start: 42
split_seed_count: 100