lines <- readLines("scripts/classify_adjusters.R")
start_ruvr <- which(grepl("# Step 1: Fit initial model to get residuals", lines))[1]
start_yugene <- which(grepl("} else if \\(method == \"yugene\"\\) \\{", lines))[1]

if (is.na(start_ruvr) || is.na(start_yugene)) {
  stop("Could not find start/end markers")
}

new_code <- c(
"      # Step 1: Fit initial model to get residuals",
"      design <- model.matrix(~ group)",
"      # We use simple linear regression to get residuals for the factors",
"      # as we are in a continuous (log-expression) space.",
"      residuals <- matrix(NA, nrow = nrow(dat), ncol = ncol(dat))",
"      for (i in 1:nrow(dat)) {",
"        fit <- lm(dat[i, ] ~ group)",
"        residuals[i, ] <- residuals(fit)",
"      }",
"      ",
"      # Step 2: Apply RUVr",
"      k <- 3",
"      # RUVr needs a matrix of expression and a vector of genes to use (all genes here)",
"      # We pass the log-data directly and set isLog=TRUE.",
"      ruv_res <- RUVSeq::RUVr(as.matrix(dat), c(1:nrow(dat)), k=k, residuals=residuals, isLog=TRUE)",
"      dat_corrected <- ruv_res$normalizedCounts",
"      ",
"      # Step 3: Project test data",
"      # To avoid mean-shift distortion, we must center both datasets using training means",
"      W <- ruv_res$W",
"      gene_means <- rowMeans(dat)",
"      dat_centered <- dat - gene_means",
"      ",
"      # Estimate alpha using centered data",
"      alpha <- solve(t(W) %*% W) %*% t(W) %*% t(dat_centered)",
"      ",
"      # Center test data using training means",
"      dat_test_centered <- dat_test - gene_means",
"      ",
"      # Estimate W_test",
"      W_test <- t(dat_test_centered) %*% t(alpha) %*% solve(alpha %*% t(alpha))",
"      ",
"      # Correct test data and add means back",
"      dat_test_corrected <- dat_test_centered - t(W_test %*% alpha)",
"      dat_test_corrected <- dat_test_corrected + gene_means",
"      ",
"      cat(\"RUVr (RUVSeq) correction complete\\n\")",
"      ",
"      return(list(dat_corrected = dat_corrected, dat_test_corrected = dat_test_corrected))",
"    } else if (method == \"ruvg\") {",
"      # RUVg: Remove Unwanted Variation using housekeeping genes",
"      # Execute via official RUVSeq package",
"      cat(\"Applying RUVg correction via RUVSeq...\\n\")",
"      ",
"      if (!requireNamespace(\"RUVSeq\", quietly = TRUE)) {",
"        stop(\"Package 'RUVSeq' is required but not installed.\")",
"      }",
"      ",
"      # Define housekeeping genes",
"      housekeeping_genes <- c(\"GAPDH\", \"ACTG1\", \"RPS18\", \"POM121C\", \"MRPL18\", ",
"                             \"TOMM5\", \"YTHDF1\", \"TPT1\", \"RPS27\")",
"      available_hk <- intersect(housekeeping_genes, rownames(dat))",
"      ",
"      if (length(available_hk) < 2) {",
"        cat(\"WARNING: Fewer than 2 housekeeping genes found in the top features. Falling back to unadjusted data for this method.\\n\")",
"        return(list(dat_corrected = dat, dat_test_corrected = dat_test))",
"      }",
"      ",
"      # Apply RUVg",
"      k <- min(3, length(available_hk) - 1)",
"      ruv_res <- RUVSeq::RUVg(as.matrix(dat), available_hk, k=k, isLog=TRUE)",
"      dat_corrected <- ruv_res$normalizedCounts",
"      ",
"      # Step 2: Project test data using the loadings (alpha) from training",
"      # To avoid mean-shift distortion, we must center both datasets using training means",
"      W <- ruv_res$W",
"      gene_means <- rowMeans(dat)",
"      dat_centered <- dat - gene_means",
"      ",
"      # Estimate alpha for all genes using centered data",
"      alpha <- solve(t(W) %*% W) %*% t(W) %*% t(dat_centered)",
"      ",
"      # For RUVg, we estimate W_test using only the housekeeping genes",
"      alpha_hk <- alpha[, which(rownames(dat) %in% available_hk), drop=FALSE]",
"      dat_test_hk_centered <- dat_test[available_hk, , drop=FALSE] - gene_means[available_hk]",
"      ",
"      # Estimate W_test",
"      W_test <- t(dat_test_hk_centered) %*% t(alpha_hk) %*% solve(alpha_hk %*% t(alpha_hk))",
"      ",
"      # Correct test data and add means back",
"      dat_test_centered <- dat_test - gene_means",
"      dat_test_corrected <- dat_test_centered - t(W_test %*% alpha)",
"      dat_test_corrected <- dat_test_corrected + gene_means",
"      ",
"      cat(\"RUVg (RUVSeq) correction complete\\n\")",
"      ",
"      return(list(dat_corrected = dat_corrected, dat_test_corrected = dat_test_corrected))"
)

final_lines <- c(lines[1:(start_ruvr-1)], new_code, lines[start_yugene:length(lines)])
writeLines(final_lines, "scripts/classify_adjusters.R")
