# config.yaml


output_folder: "/home/aw998/confounded_analysis/grp_batch_effects/outputs"
data_folder: "/home/aw998/confounded_analysis/grp_batch_effects/data"

adjuster: ["gmm", "min_mean", "mnn", "log_combat", "log_transformed"]
dataset_ids:
  - "gse19615"
  - "gse20194"
  - "gse20271"
  - "gse23720"
  - "gse25055"
  - "gse25065"
  - "gse31448"
  - "gse45255"
  - "gse58644"
  - "gse62944_tumor"
  - "gse76275"
  - "gse81538"
  - "gse96058_hiseq"
  - "gse96058_nextseq"
  - "metabric"

