[project]
name = "$PROJECT_NAME"
r_version = "$R_VERSION"

# Use Posit Package Manager to get fast binary installs on Linux
repositories = [
    { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
]

# Declare your project's R package dependencies here
dependencies = [
    "tidyverse",
    "rmarkdown",
    "shiny"
]